language: rust

rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly

os:
  - linux

before_install:
  - source $HOME/.nvm/nvm.sh
  - nvm install 8
  - nvm use 8

script:
  - |
      cd ratel && cargo test --verbose &&
      cd ../ratel-visitor && cargo test --verbose &&
      cd ../ffi && npm i && npm test
