[package]
name = "ratel"
version = "0.4.0"
authors = ["Maciej Hirsz <maciej.hirsz@gmail.com>"]
license = "MIT"
description = "JavaScript transpiler in Rust"
repository = "https://github.com/ratel-rust/ratel-core"
documentation = "https://github.com/ratel-rust/ratel-core"
